### ISSUE TITLE
0xumarkhatab - M-8 Precision Loss in Master Router Remove Liquidity functions

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-02-jala-swap-judging#102]
0xumarkhatab

medium

# M-8 Precision Loss in Master Router Remove Liquidity functions

## Summary
Remove liquidity functions inside Jala Master Router are prone to precision loss due to division before multiplication.

## Vulnerability Detail
Inside Jala Master Router Remove Liquidity functions,  The protocol calculates the returned amount after liquidity this way

```solidity

        uint256 tokenAReturnAmount = (amountA / tokenAOffset) * tokenAOffset;
        uint256 tokenBReturnAmount = (amountB / tokenBOffset) * tokenBOffset;

```
And then sends it to users.
However, due to Division before multiplication, this approach is prone to Precision loss
and can cause unfavorable situations where funds transacted might be less than intended

## Impact
Loss of precision in dealing with tokens Amount

## Code Snippet
https://github.com/sherlock-audit/2024-02-jala-swap/blob/main/jalaswap-dex-contract/contracts/JalaMasterRouter.sol#L129

## Tool used

Manual Review

## Recommendation
Try multiplying by TokenOffset first instead of division.

```solidity

        uint256 tokenAReturnAmount = (amountA * tokenAOffset) / tokenAOffset;
        uint256 tokenBReturnAmount = (amountB /*tokenBOffset) / tokenBOffset;

```

**Comment by 0xumarkhatab** [comment]
if the amountA and amountB are less than tokenAOffset and tokenBOffset, solidity will clearly round the number down to 0 .
as tokenAOffset and tokenBOffset are bigger numbers i.e order of 10^decimals , if the amounts of tokens range from 
0.1-0.99 ERC20 token ,the returned amount will be zero that will cause plain funds loss to user !

@nevillehuang

**Comment by nevillehuang** [comment]
@0xumarkhatab You are not supposed to add additional proof during escalation period, and so this should remain invalid. Besides from comments in #104 and #158 you will realise there is no loss
